# Config file for automatic testing at travis-ci.org

language: python
sudo: false
cache: pip
python:
  - "3.6"
  - "3.5"
  - "2.7"
  - "pypy"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - pip install -U pip

install:
  - pip install -U .
  - pip install -U -r dev-requirements.txt

before_script:
  - flake8 .

script: py.test tests
